name: Medium Timeline Checks (Leslie's, Pumphouse)

on:
  schedule:
    - cron: '0 */2 * * *'  # Every 2 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  telemetry:
    runs-on: ubuntu-latest
    env:
      GH_REPO: brianhartsell/oakspool
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      SLACK_BOARD_CHANNEL: ${{ secrets.SLACK_BOARD_CHANNEL }}
      SLACK_HEARTBEAT_CHANNEL: ${{ secrets.SLACK_HEARTBEAT_CHANNEL }}
      LESLIES_USERNAME: ${{ secrets.LESLIES_USERNAME }}
      LESLIES_PASSWORD: ${{ secrets.LESLIES_PASSWORD }}
      LESLIES_POOLID: ${{ secrets.LESLIES_POOLID }}
      LESLIES_POOLNAME: ${{ secrets.LESLIES_POOLNAME }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and set TZ
        run: |
          pip install beautifulsoup4 matplotlib pandas requests python-dotenv pytz
          export TZ="America/Chicago"

      - name: Run Leslies Summary
        run: python leslies-log-and-plot.py   

      - name: Run Pump House Update  
        run: python pumphouse.py    

      - name: Commit telemetry and dashboard updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add logs/*.csv docs/*.png

          git status
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Leslies/pumphouse update on $(date '+%Y-%m-%d %H:%M %Z')"
            git fetch origin main
            git pull --rebase origin main
            git push
          fi          
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

