name: PoolCam Snapshot

on:
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Start Eufy WebSocket bridge (Docker)
        run: |
          docker run -d \
            -e USERNAME=${{ secrets.EUFY_USER }} \
            -e PASSWORD=${{ secrets.EUFY_PASS }} \
            -e DEVICE_ID=poolcam-ci-ephemeral \
            -e COUNTRY=US \
            -e LANGUAGE=en \
            -p 3000:3000 \
            bropat/eufy-security-ws:latest
          sleep 30

      - name: Set PIN_REQUIRED flag
        run: echo "PIN_REQUIRED=${{ steps.session-cache.outputs.cache-hit != 'true' }}" >> $GITHUB_ENV

      - name: Verify Safety PIN
        if: env.PIN_REQUIRED == 'true'
        run: |
          curl -X POST http://localhost:3000/login/verifyCode \
            -H 'Content-Type: application/json' \
            -d "{\"code\":\"${{ secrets.EUFY_PIN }}\"}"
          sleep 5

      - name: Install Python dependencies
        run: pip install websockets python-ffmpeg

      - name: Run flowmeter script
        env:
          EUFY_PIN: ${{ secrets.EUFY_PIN }}
        run: python flowmeter.py

      - name: Upload frame
        uses: actions/upload-artifact@v4
        with:
          name: poolcam-frame
          path: flow_reading.jpg
