name: PoolCam Snapshot

on:
  workflow_dispatch:  # ✅ Manual trigger only

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.5.0'

      - name: Start WebSocket bridge (Docker)
        run: |
          docker run -d \
            -e USERNAME=${{ secrets.EUFY_USER }} \
            -e PASSWORD=${{ secrets.EUFY_PASS }} \
            -e DEVICE_ID=pull-from-github-87432 \
            -e COUNTRY=US \
            -e LANGUAGE=en \
            -p 3000:3000 \
            bropat/eufy-security-ws
          sleep 10

      - name: Install Python dependencies
        run: pip install websockets python-ffmpeg

      - name: Run flowmeter script
        run: python flowmeter.py

      - name: Upload frame
        uses: actions/upload-artifact@v4
        with:
          name: poolcam-frame
          path: flow_reading.jpg
