name: PoolCam Snapshot

on:
  workflow_dispatch:  # ✅ Manual trigger only

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.5.0'

      - name: Create session volume directory
        run: mkdir -p ./eufy-session

      - name: Start WebSocket bridge (Docker)
        run: |
          docker run -d \
            -e USERNAME=${{ secrets.EUFY_USER }} \
            -e PASSWORD=${{ secrets.EUFY_PASS }} \
            -e DEVICE_ID=persistent-ci-bridge-001 \
            -e COUNTRY=US \
            -e LANGUAGE=en \
            -v ${{ github.workspace }}/eufy-session:/data \
            -p 3000:3000 \
            bropat/eufy-security-ws:latest
          sleep 30  # Allow bridge to initialize

      - name: Submit Safety PIN (if needed)
        if: ${{ secrets.EUFY_PIN != '' }}
        run: |
          docker exec $(docker ps -q --filter ancestor=bropat/eufy-security-ws) \
            node cli.js verifyCode ${{ secrets.EUFY_PIN }}

      - name: Install Python dependencies
        run: pip install websockets python-ffmpeg

      - name: Run flowmeter script
        run: python flowmeter.py

      - name: Upload frame
        uses: actions/upload-artifact@v4
        with:
          name: poolcam-frame
          path: flow_reading.jpg
