name: Daily Telemetry & Dashboard Update

on:
  schedule:
    - cron: '0 5 * * *'  # Daily at 11PM CDT (5 UTC)
  workflow_dispatch:

jobs:
  telemetry:
    runs-on: ubuntu-latest
    env:
      GH_REPO: brianhartsell/oakspool
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_HEARTBEAT_CHANNEL: ${{ secrets.SLACK_HEARTBEAT_CHANNEL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Run flume constant water check
        run: python flume_constant_water_check.py

      - name: Run flume water usage logger
        run: python flume_water_use.py

      - name: Update and publish dashboard
        run: python dashboard_update.py
