name: Nightly Flume Usage Summary

on:
  schedule:
    - cron: '0 4 * * *'  # 11 PM CDT = 04:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  telemetry:
    runs-on: ubuntu-latest
    env:
      GH_REPO: brianhartsell/oakspool
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      SLACK_HEARTBEAT_CHANNEL: ${{ secrets.SLACK_HEARTBEAT_CHANNEL }}
      FLUME_USERNAME: ${{ secrets.FLUME_USERNAME }}
      FLUME_PASSWORD: ${{ secrets.FLUME_PASSWORD }}
      FLUME_CLIENT_ID: ${{ secrets.FLUME_CLIENT_ID }}
      FLUME_CLIENT_SECRET: ${{ secrets.FLUME_CLIENT_SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install matplotlib pandas requests python-dotenv pytz

      - name: Run Flume usage summary
        run: python flume_water_use.py

      - name: Upload usage summary file
        uses: actions/upload-artifact@v4
        with:
          name: flume-summary
          path: output/summary.txt
      
      - name: Commit output artifacts to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      
          # Ensure directories are visible to Git
          git add output/summary.txt
          git add docs/flume_usage_chart.png
          git add docs/flume_season_comparison.png
          git add logs/flume_usage_log.csv
          git add heartbeats/flume_heartbeat_usage.log
          git add flume_log_backup/
      
          git commit -m "Add telemetry outputs from nightly run on $(date '+%Y-%m-%d')"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
