name: Nightly Flume Usage Summary

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  telemetry:
    runs-on: ubuntu-latest
    env:
      GH_REPO: brianhartsell/oakspool
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_HEARTBEAT_CHANNEL }}
      SLACK_HEARTBEAT_CHANNEL: ${{ secrets.SLACK_HEARTBEAT_CHANNEL }}
      FLUME_USERNAME: ${{ secrets.FLUME_USERNAME }}
      FLUME_PASSWORD: ${{ secrets.FLUME_PASSWORD }}
      FLUME_CLIENT_ID: ${{ secrets.FLUME_CLIENT_ID }}
      FLUME_CLIENT_SECRET: ${{ secrets.FLUME_CLIENT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install matplotlib pandas requests python-dotenv pytz

      - name: Run Flume usage summary
        run: python flume_water_use.py

      - name: Run dashboard update
        run: python dashboard_update.py

      - name: Commit telemetry and dashboard updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add docs/index.html
          git add docs/flume_usage_chart.png
          git add docs/flume_season_comparison.png
          git add logs/flume_usage_log.csv
          git add heartbeats/flume_heartbeat_usage.log
          git add flume_log_backup/

          git commit -m "Telemetry + dashboard update from nightly run on $(date '+%Y-%m-%d')"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Push safely to dev
        run: |
          git fetch origin dev
          git diff --quiet HEAD origin/dev || git pull --rebase origin dev
          git push origin dev
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
