name: Nightly Flume Usage Summary

on:
  schedule:
    - cron: '0 4 * * *'  # 11 PM CDT = 04:00 UTC
  workflow_dispatch:

jobs:
  telemetry:
    runs-on: ubuntu-latest
    env:
      GH_REPO: brianhartsell/oakspool
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      SLACK_HEARTBEAT_CHANNEL: ${{ secrets.SLACK_HEARTBEAT_CHANNEL }}
      FLUME_USERNAME: ${{ secrets.FLUME_USERNAME }}
      FLUME_PASSWORD: ${{ secrets.FLUME_PASSWORD }}
      FLUME_CLIENT_ID: ${{ secrets.FLUME_CLIENT_ID }}
      FLUME_CLIENT_SECRET: ${{ secrets.FLUME_CLIENT_SECRET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install matplotlib pandas requests python-dotenv pytz

      - name: Run Flume usage summary
        run: python flume_water_use.py

      - name: Upload usage summary file
        uses: actions/upload-artifact@v4
        with:
          name: flume-summary
          path: output/summary.txt
